### ISSUE TITLE
Update cloud function to 2nd generation

### ISSUE THREAD

**Issue by 50Fifty** [50Fifty/backup-firebase-auth#13]

**Comment by 50Fifty** [comment]
Firebase team confirmed that scheduled functions are not available in 2nd generation cloud functions. Will stick with 1st generation.

**Comment by synchrone** [comment]
Schedule is now supported in 2nd gen Functions https://firebase.google.com/docs/functions/schedule-functions

**Comment by 50Fifty** [comment]
> Schedule is now supported in 2nd gen Functions https://firebase.google.com/docs/functions/schedule-functions

Hey @synchrone , SFLR. Schedule is supported as 2nd generation function but Firebase Extensions does not support 2nd generation scheduled functions. https://firebase.google.com/docs/extensions/publishers/functions#scheduled
